name: Build xemu-win64-toolchain

on: [push, pull_request]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: mborgerson/xxx

jobs:
  build-image:
    name: Build and Publish Image
    if: github.repository_owner == 'mborgerson'
    runs-on: ubuntu-latest
    steps:
      - name: Clone tree
        uses: actions/checkout@v3

      - name: Extract image metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v3.2.0
        with:
          # context: ubuntu-win64-cross
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
